import { useCallback, useEffect, useMemo, useState } from 'react'
import { io } from 'socket.io-client'
import { Activity, Bell, Download, Droplets, Pause, Play, Radio, Settings2, Sparkles, Thermometer, Waves } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const API = import.meta.env.VITE_API_URL || '/api'
type Metric = 'temperature' | 'humidity' | 'vibration'
type Reading = {sensorId:string;location:string;metric:Metric;value:number;unit:string;timestamp:string;anomaly?:boolean}
type Insight = {metric:Metric;average:string;minimum:number;maximum:number;samples:number}
type Setting = {metric:Metric;minValue:number|null;maxValue:number|null}
const meta={temperature:{label:'Temperature',icon:Thermometer,color:'#ff7a59',unit:'°C'},humidity:{label:'Humidity',icon:Droplets,color:'#5c8dff',unit:'%'},vibration:{label:'Door activity',icon:Waves,color:'#a47cf3',unit:'events'}} as const
async function json<T>(path:string):Promise<T>{const r=await fetch(`${API}${path}`);if(!r.ok)throw new Error(`Request failed: ${r.status}`);return r.json()}

function ValueCard({metric,reading,connected}:{metric:Metric;reading?:Reading;connected:boolean}){const m=meta[metric],Icon=m.icon;return <article className="value-card" style={{'--accent':m.color} as React.CSSProperties}><div className="card-top"><span className="icon-wrap"><Icon size={20}/></span><span className="live-dot">{connected?'LIVE':'WAITING'}</span></div><p>{m.label}</p><div className="metric-value">{reading?reading.value:'—'}<small>{metric==='vibration'?'':reading?.unit||m.unit}</small></div><div className="card-foot"><span>{reading?.location||(metric==='vibration'?'Front Door':'Bathroom')}</span><span>{reading?new Date(reading.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'No data'}</span></div></article>}

function App(){
 const [latest,setLatest]=useState<Partial<Record<Metric,Reading>>>({}),[series,setSeries]=useState<Partial<Record<Metric,Reading[]>>>({}),[activity,setActivity]=useState<Array<{activity:number;timestamp:string}>>([]),[insights,setInsights]=useState<Insight[]>([]),[settings,setSettings]=useState<Setting[]>([]),[connected,setConnected]=useState(false),[paused,setPaused]=useState(false),[range,setRange]=useState(24),[selected,setSelected]=useState<Metric>('temperature'),[alerts,setAlerts]=useState<Reading[]>([]),[error,setError]=useState('')
 const load=useCallback(async()=>{try{const [s,t,h,v,a,i,l]=await Promise.all([json<Reading[]>('/sensors'),json<Reading[]>(`/readings?metric=temperature&hours=${range}`),json<Reading[]>(`/readings?metric=humidity&hours=${range}`),json<Reading[]>(`/readings?metric=vibration&hours=${range}`),json<Array<{activity:number;timestamp:string}>>(`/activity?hours=${range}`),json<{readings:Insight[]}>('/insights'),json<Setting[]>('/settings')]);setLatest(Object.fromEntries(s.map(r=>[r.metric,r])));setSeries({temperature:t,humidity:h,vibration:v});setActivity(a);setInsights(i.readings);setSettings(l);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load dashboard')}},[range])
 useEffect(()=>{load()},[load]);useEffect(()=>{const s=io({path:'/socket.io',transports:['websocket','polling']});s.on('connect',()=>setConnected(true));s.on('disconnect',()=>setConnected(false));s.on('reading',(r:Reading)=>{if(paused)return;setLatest(v=>({...v,[r.metric]:r}));setSeries(v=>({...v,[r.metric]:[...(v[r.metric]||[]).slice(-119),r]}));if(r.anomaly)setAlerts(v=>[r,...v].slice(0,5))});return()=>{s.disconnect()}},[paused])
 const chartData=useMemo(()=>(series[selected]||[]).map(r=>({time:new Date(r.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),value:r.value})),[series,selected]);const activityData=useMemo(()=>activity.slice(-96).map(x=>({time:new Date(x.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),value:+x.activity})),[activity]);const insight=insights.find(x=>x.metric===selected)
 return <main><header><div className="brand"><div className="logo"><Radio/></div><div><h1>Haven<span>Pulse</span></h1><p>HOME INTELLIGENCE</p></div></div><div className="header-actions"><div className={`status ${connected?'online':''}`}><i/>{connected?'Systems online':'Reconnecting'}</div><button className="icon-button" title="Alerts"><Bell size={19}/>{alerts.length>0&&<b>{alerts.length}</b>}</button><div className="avatar">AP</div></div></header>
 <section className="hero"><div><p className="eyebrow">WIFI MOTION NETWORK · 01</p><h2>Your home, in rhythm.</h2><p>Live environmental intelligence with calm, actionable context.</p></div><div className="hero-actions"><select value={range} onChange={e=>setRange(+e.target.value)}><option value="6">Last 6 hours</option><option value="24">Last 24 hours</option><option value="168">Last 7 days</option></select><button className="pause" onClick={()=>setPaused(!paused)}>{paused?<Play size={17}/>:<Pause size={17}/>} {paused?'Resume live':'Pause live'}</button></div></section>{error&&<div className="error">{error} <button onClick={load}>Try again</button></div>}
 <section className="value-grid"><ValueCard metric="temperature" reading={latest.temperature} connected={connected}/><ValueCard metric="humidity" reading={latest.humidity} connected={connected}/><ValueCard metric="vibration" reading={latest.vibration} connected={connected}/><article className="insight-card"><span><Sparkles size={18}/> AMBIENT INSIGHT</span><h3>{latest.humidity?.value&&latest.humidity.value>65?'Humidity is running high.':'Everything feels balanced.'}</h3><p>{alerts.length?`${alerts.length} recent threshold event${alerts.length>1?'s':''} need attention.`:'Temperature and humidity are within your comfort thresholds.'}</p></article></section>
 <section className="content-grid"><article className="panel chart-panel"><div className="panel-title"><div><p className="eyebrow">ENVIRONMENT</p><h3>Room conditions</h3></div><div className="tabs">{(['temperature','humidity','vibration'] as Metric[]).map(m=><button className={selected===m?'active':''} onClick={()=>setSelected(m)} key={m}>{meta[m].label}</button>)}</div></div><div className="chart-stat"><strong>{insight?.average??latest[selected]?.value??'—'}</strong><span>{selected==='vibration'?'events':meta[selected].unit} avg</span>{insight&&<em>Range {insight.minimum}–{insight.maximum}</em>}</div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={meta[selected].color} stopOpacity={.3}/><stop offset="100%" stopColor={meta[selected].color} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 6" vertical={false} stroke="#26344a"/><XAxis dataKey="time" tick={{fill:'#77859b',fontSize:11}} axisLine={false} tickLine={false} minTickGap={45}/><YAxis tick={{fill:'#77859b',fontSize:11}} axisLine={false} tickLine={false} width={35}/><Tooltip contentStyle={{background:'#101827',border:'1px solid #29364a',borderRadius:12}}/><Area type="monotone" dataKey="value" stroke={meta[selected].color} strokeWidth={2.5} fill="url(#fill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></article>
 <aside className="panel activity-panel"><div className="panel-title"><div><p className="eyebrow">MOTION SIGNATURE</p><h3>Daily rhythm</h3></div><Activity size={20}/></div><div className="chart mini"><ResponsiveContainer width="100%" height="100%"><BarChart data={activityData}><Bar dataKey="value" fill="#43d4a0" radius={[3,3,0,0]}/><Tooltip contentStyle={{background:'#101827',border:'1px solid #29364a',borderRadius:12}}/></BarChart></ResponsiveContainer></div><div className="motion-scale"><span>Still</span><span>Active</span></div><p className="activity-note"><i/> Pattern looks normal for this home</p></aside></section>
 <section className="bottom-grid"><article className="panel alert-panel"><div className="panel-title"><div><p className="eyebrow">SMART GUARD</p><h3>Thresholds</h3></div><Settings2 size={19}/></div>{settings.map(s=><div className="threshold" key={s.metric}><span style={{background:meta[s.metric].color}}/><div><strong>{meta[s.metric].label}</strong><small>{s.metric==='vibration'?'Notify on every event':`${s.minValue}–${s.maxValue} ${meta[s.metric].unit}`}</small></div><b>Armed</b></div>)}</article><article className="panel stream-panel"><div className="panel-title"><div><p className="eyebrow">EVENT STREAM</p><h3>Latest signals</h3></div><a href={`${API}/export.csv?metric=${selected}`}><Download size={17}/> Export CSV</a></div>{Object.values(latest).filter(Boolean).map(r=><div className="event" key={r!.metric}><i style={{background:meta[r!.metric].color}}/><div><strong>{r!.location}</strong><small>{meta[r!.metric].label} · {new Date(r!.timestamp).toLocaleString()}</small></div><b>{r!.value} {r!.metric==='vibration'?'':r!.unit}</b></div>)}</article></section><footer>HAVENPULSE <span>·</span> Local-first sensor intelligence <span>·</span> Real-time MQTT telemetry</footer></main>
}
export default App
